### ISSUE TITLE
[N64] Conker's Bad Fur Day (USA) - Graphical artifacts when pausing

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#186]
Occasionally, when you pause ingame, artifacts will appear at the top of the screen. To reproduce, simply pause and unpause repeatedly during gameplay until they appear.
![image](https://user-images.githubusercontent.com/50224630/133582401-14401631-a57b-4b92-86e8-8de9e0563985.png)
![image](https://user-images.githubusercontent.com/50224630/133582411-bc7d005a-ca14-42c7-bb0c-38ead3d77d6c.png)

Tested on Ares v123, compiled 9/16/2021, on Linux Mint 20.

**Comment by Shideravan** [comment]
Not seem to be reproducible in 9f55e66 anymore. Probably fixed with parallel-rdp update in the most recent revision.
![image](https://user-images.githubusercontent.com/12163923/133870744-61733971-f808-4220-bf54-4ff22551fab7.png)

![image](https://user-images.githubusercontent.com/12163923/133869921-031919cb-a70b-4074-ba9f-0bd1fc100cf0.png)

**Comment by Shideravan** [comment]
The game doesn't seem to be properly saving tho

**Comment by HeroponRikiBestest** [comment]
I an unable to test, because every N64 game crashes Ares on the latest build.

**Comment by bigbass1997** [comment]
> I an unable to test, because every N64 game crashes Ares on the latest build.

Hmm they don't crash for me on master.

**Comment by HeroponRikiBestest** [comment]
I had to recompile, N64 games work fine for me now. Anyways, it's definitely not fixed on the latest build. As I mentioned, it can take quite a few pauses before you can reproduce the issue.
![image](https://user-images.githubusercontent.com/50224630/133944986-a3e4b938-bfd8-4d58-a286-ebd85cd969ac.png)

**Comment by Shideravan** [comment]
> I had to recompile, N64 games work fine for me now. Anyways, it's definitely not fixed on the latest build. As I mentioned, it can take quite a few pauses before you can reproduce the issue.
> ![image](https://user-images.githubusercontent.com/50224630/133944986-a3e4b938-bfd8-4d58-a286-ebd85cd969ac.png)

Are you using savestates?

**Comment by HeroponRikiBestest** [comment]
No, I did not use any save states when testing, and I do not have any save states in the game to begin with. 
While it isn't related to the use of save states, I also wanted to mention that I deleted my existing cartridge save files and tried it on a new one, just to verify it still happened.
![image](https://user-images.githubusercontent.com/50224630/133946719-0d9efdba-ae35-4af3-b5c4-53e24afb744d.png)

**Comment by Shideravan** [comment]
I tried to pause/unpause a lot of times and didn't reproduced
https://youtu.be/VU7J-wHnJl8

Please, what's your N64 render Settings?
I suspect what you are experiencing is not a graphical emulation bug but rather a high-scalling side-effect. If that's the case, unfortunately maybe it isn't easy fixable, as the game wasn't projected to run in those circumstances.

**Comment by Shideravan** [comment]
I finally was able to reproduce, but only in **UHD Quality** mode
![image](https://user-images.githubusercontent.com/12163923/134274430-d5721786-9b8c-4031-b8fe-ceef66e94d64.png)

**Comment by JoshShabel** [comment]
I did all of my testing on the normal SD rendering mode, and did not upscale at any point.

**Comment by HeroponRikiBestest** [comment]
I did all my testing on SD rendering, and did not upscale. Here's a video showing proof. Sorry it's so long, but I wanted to do it on a blank save file just after compiling the latest release. I recommend skipping to the last minute or two after viewing my settings in the beginning. https://drive.google.com/file/d/11BJSrgdaN6dzrFBQiGa7Lelq2w410nMI/view?usp=sharing

> I tried to pause/unpause a lot of times and didn't reproduced
> https://youtu.be/VU7J-wHnJl8
> 
> Please, what's your N64 render Settings?
> I suspect what you are experiencing is not a graphical emulation bug but rather a high-scalling side-effect. If that's the case, unfortunately maybe it isn't easy fixable, as the game wasn't projected to run in those circumstances.

**Comment by Shideravan** [comment]
Very interesting. Thank you for share all these details with us. Don't worry about the video being long, the context is very important for reproducibility, that's why I'd asked some questions before. Nice to know the issue can be triggered in the first cutscene as in the first moment I'd though that it need to be triggered in the second area (overworld).

**Comment by HeroponRikiBestest** [comment]
Yeah, I thought so too initially, but it turns out it's just the first part of the opening cutscene (with conker sitting on the throne) that doesn't give results as often (although it sometimes still does). As soon as the camera cuts to Berri's house, I can get it much more reliably. That might just be a placebo though, I haven't exactly tested that theory.

**Comment by Shideravan** [comment]
I finaly could replicate this bug in SD, in the intro cutscene.
![image](https://user-images.githubusercontent.com/12163923/134785877-a3a6aaee-1212-4b69-8364-e0af0eaa5125.png)

Are you sure this doesn't happen in the console itself? If the answer is "no" and I had to bet, I think it's related with garbage on VRAM.

**Comment by HeroponRikiBestest** [comment]
I've never seen the bug happen on console. If you have proof of otherwise, let me know.

**Comment by HeroponRikiBestest** [comment]
Unable to recreate on lastest master. Can someone else test, since Shideravan's testing seems to indicate this issue's frequency can vary between computers?

**Comment by kev4cards** [comment]
Still happening:
![Conker's Bad Fur Day (U)  !  2022-07-05 23-38-38](https://user-images.githubusercontent.com/21962903/177463687-89965cd8-db79-4f7b-a0b0-aba359af93e3.png)
![Conker's Bad Fur Day (U)  !  2022-07-05 23-39-18](https://user-images.githubusercontent.com/21962903/177463695-048d209d-1afe-4bb4-a065-cb6bb17ea715.png)

**Comment by kev4cards** [comment]
Found this issue to be a regression. Commit 8c7bad1 (ares v120r03) causes the corrupted line to appear. There are numerous timing changes and additions to this commit.

**Comment by Shideravan** [comment]
Is this fixed? I wasn't able to reproduce anymore at v134
![image](https://github.com/ares-emulator/ares/assets/12163923/73ef0539-276a-456f-867b-8d4ee1484392)

**Comment by RinMaru** [comment]
yes this is fixed

**Comment by kev4cards** [comment]
Still exists but much less frequent:

![CBFD ares v134](https://github.com/ares-emulator/ares/assets/21962903/eb8cbd4b-b7ec-42d3-8fe4-f60e15bc06a7)

**Comment by YourEverydayTiredToast** [comment]
Like this?

![Image](https://github.com/user-attachments/assets/8186f56f-04ae-4fb1-bd64-94dd21292c5e)
