### ISSUE TITLE
improve menubar text visibility with gtk3

### ISSUE THREAD

**Issue by galtgendo** [higan-emu/ares#229]
This isn't a complete/fully correct solution, but still an improvement.

in hiro/gtk/application.cpp, within that css block you add 'menubar {background-color: gray;}', background changes and text gains reasonable visibility.

Also, regardless, at the end of that block there should be 'g_object_unref(provider);' to release one reference to the previously created object.

**Comment by Screwtapello** [comment]
Hm, this should have been fixed in https://github.com/ares-emulator/ares/pull/126. What version of ares are you testing with?

**Comment by galtgendo** [comment]
> Hm, this should have been fixed in #126. What version of ares are you testing with?

As the other issue I filed suggests, v124.

**Comment by tobihan** [comment]
With gtk3 I still have a black menu bar with black text in ares v126.
