### ISSUE TITLE
[MD] Triple Play Gold: Doesn't launch

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#242]
Ares - Just black screen
![2021-10-18 03_05_16-Triple Play Gold (U)  c !](https://user-images.githubusercontent.com/88586431/137643189-b7746690-4361-4816-aefb-4cd867d2baca.png)
BlastEm
![2021-10-18 03_05_45-Triple Play Gold - BlastEm - 59 9 fps](https://user-images.githubusercontent.com/88586431/137643211-c257f1e3-ab03-47fe-b18f-56a2530e47ab.png)

Triple Play Gold (U) [c][!]
SHA1 007BEE242384DB1887C5831657470584FF77A163

Tested on ares nightly 2021-10-17

**Comment by BiZkViT96** [comment]
Fixed with https://github.com/ares-emulator/ares/pull/257

**Comment by Shideravan** [comment]
Not fixed for me with latest ares 7810a05
![image](https://user-images.githubusercontent.com/12163923/138334459-e605c21d-b549-4207-8bcb-a5caa1655b89.png)

SHA-1: 791AFD91483A332EC5CA3384EE791252767F2F67
MD5: FB2F3C6FE0C3BA9FD55DC64E8CD8EC74

(My dump matches No-Intro's checksum)

**Comment by Shideravan** [comment]
Even matching the checksum, the dump aren't working in any emulator. Another dump of the same game, with the same checksum is running fine. Weird.
![image](https://user-images.githubusercontent.com/12163923/138339320-defb10ee-fc53-4d6c-b26e-0ef5f8978e3c.png)

Edit: the header was incorrect. Not a issue with ares then.
