### ISSUE TITLE
[N64] Gauntlet Legends: Game hangs at variable times

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#548]
Ares version: https://github.com/ares-emulator/ares/commit/3aa1b3b7389dffd0aff4f432de62f0ec9e764c8b

Now with the recent updates from @rasky the game boots. Unfortunatelly thou, the game will hang just after few seconds of the first cutscene (the game intro)

**Comment by kev4cards** [comment]
For reference, abf4c58 is the commit that allowed the game to boot.

For me, the game hangs after the Midway logo screen. Is that the cut scene you are referring to?

**Comment by Shideravan** [comment]
No, the game runs the beginning of the intro cutscene
![image](https://user-images.githubusercontent.com/12163923/167268815-26d7074c-1ecc-4a31-a864-3ddf82b00939.png)

**Comment by kev4cards** [comment]
Okay. I get that result, too. I was worried there was going to be some strange system-specific difference.

I did not check the MAME renderer out of laziness, and most times, it fails in the same spot as the vulkan renderer (ParaLLEl-RDP). That's weird that the vulkan renderer does not show that.

**Comment by remutro** [comment]
I'm not sure there is a difference here between using the MAME renderer and Parallel-RDP, other then perhaps a timing difference. If you load the PAL or Japanese ROM, it will hang at the same exact spot using Parallel-RDP.

**Comment by kev4cards** [comment]
I don't believe there is either. The root cause of the problem definitely lies outside of the renderer. MAME was probably just able to present those frames at just slightly different times, causing them to appear. So, the hang on the black screen just before the cut scene and the hang at the very beginning of the cut scene are one and the same. Just weird from a reporting perspective.

**Comment by kev4cards** [comment]
The Japanese version is now playable as of commit 8236464. The first commit of the PIF refactor (96a6f98) is responsible for the change in status (hidden by the temporary input issue). The other versions remain unchanged.

EDIT: After discussion with Rasky about trying 8236464 without the reading/writing to PIF and RDRAM part to see if that was the actual fix (it was not), I decided to check the commit prior to the PIF refactor. That commit allowed the game to work, even though I thought I had checked it and found it to be failing. As a result, I checked the remaining commits from that PR batch. Commit 32ba2fe is what actually fixed the Japanese version of Gauntlet Legends.

**Comment by Shideravan** [comment]
It's seems fixed in the latest ares build.

**Comment by kev4cards** [comment]
I just tried this with Gauntlet Legends (E). It hanged on the character select screen. So, the issue, most likely, still exists, just in a different spot.

**Comment by Shideravan** [comment]
Gauntlet Legends (Europe) is working properly in ares v134

![image](https://github.com/ares-emulator/ares/assets/12163923/4f956109-6e0e-44e0-abdc-1c6e5f87e923)

**Comment by kev4cards** [comment]
The issue title here should be updated. The game can certainly hang in the opening intro, or it can hang well into the second level, for example. Therefore, the game is inconsistent from commit to commit regarding this behavior. "Game hangs at variable times" might be a better reflection of the issue.
